name: Summarize Projects

on:
  push:
    branches:
      - main
    paths:
      - '**/README.md'

jobs:
  summarize-projects:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install -r requirements.txt

      - name: Process README
        run: python scripts/process_readme_hf.py

      - name: Upload summaries
        uses: actions/upload-artifact@v4
        with:
          name: project-summaries
          path: |
            **/project_summary_hf.json

      - name: Update website
        run: |
          # Add steps to update your website here
          # This could be pushing to your website's repository
          # or deploying to your hosting platform 