name: Summarize Projects

on:
  repository_dispatch:
    types: [summarize_repo]
  push:
    branches:
      - main
    paths:
      - '**/README.md'
      - '.github/workflows/summarize-projects.yml'

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project-summarizer (this repo with script)
        uses: actions/checkout@v4
        with:
          path: summarizer

      - name: Checkout target repo to summarize
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub

      - name: Process README
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
        run: |
          python summarizer/scripts/process_readme_llm.py
        working-directory: target-repo

      - name: Checkout summaries repository
        uses: actions/checkout@v4
        with:
          repository: nnigam96/project-summaries
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: summaries

      - name: Save summary
        run: |
          mkdir -p summaries/${{ github.event.client_payload.repository_name }}
          cp target-repo/project_summary_llm.json summaries/${{ github.event.client_payload.repository_name }}/summary.json

      - name: Commit and push summary
        run: |
          cd summaries
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/nnigam96/project-summaries.git
          git add .
          git commit -m "Update summary for ${{ github.event.client_payload.repository_name }}" || echo "No changes to commit"
          git push