name: Summarize Projects

on:
  push:
    paths:
      - '**/README.md'
      - '.github/workflows/summarize-projects.yml'

jobs:
  summarize:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Process README
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
        run: |
          python scripts/process_readme_llm.py
          
      - name: Upload summary
        uses: actions/upload-artifact@v4
        with:
          name: project-summary
          path: project_summary_llm.json

      - name: Update website
        run: |
          # Add steps to update your website here
          # This could be pushing to your website's repository
          # or deploying to your hosting platform 